# This file must be put in the launch.json / env variable in a minified version
# https://onlineyamltools.com/minify-yaml
appCards:
  - micro:
      link: https://micro.dev.fedodo.social
      image: https://fedodo.org/images/Fedodo%20Circle.png
  - micro2:
      link: https://micro.dev.fedodo.social
      image: https://fedodo.org/images/Fedodo%20Circle.png