name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  VERSION: 0.2.${{ github.run_number }}
  FLUTTER_VERSION: "3.7.12"

jobs:
  BuildWeb:
    runs-on: ubuntu-latest

    steps:
      - uses: Fedodo/Fedodo.Pipelines/BuildContainerFlutter@main
        with:
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
          REPO: "fedodo.ui.home"
          TAG_PREFIX: ""
